# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes

pages:
    name: Pages
    singular_name: Page
    description: Pages - available as /<page_slug> too
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    recordsperpage: 100
    icon_many: fa:file-text

members:
    name: Members
    singular_name: Member
    slug: members
    singular_slug: member
    fields:
        title:
            type: text
            class: large
            label: Name
            group: content
        slug:
            type: slug
            uses: title
        bio:
            type: markdown
        image:
            type: image
        youtube_channel_id:
            type: text
            label: Youtube Channel ID
            info: "24 character channel ID (eg. URL https://www.youtube.com/channel/[channel_id]). For yourself can be found on https://www.youtube.com/account_advanced"
            postfix: "<p>Youtube API will be queried for this ID to automatically update the fields bellow on page creation and once an hour.</p>"
            group: Youtube
        youtube_subscribers:
            type: biginteger
            label: Youtube Subscribers
        youtube_videos:
            type: integer
            label: Youtube Videos
        youtube_views:
            type: biginteger
            label: Youtube Views
        youtube_trailer:
            type: text
            label: Youtube Trailer Video ID
    sort: title
    show_on_dashboard: false
    icon_many: fa:users
    icon_one: fa:user

posts:
    name: News
    singular_name: News Item
    slug: news
    singular_slug: news-item
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        image:
            type: image
    icon_many: fa:newspaper-o

events:
    name: Events
    singular_name: Event
    listing_sort: -event_time
    sort: -event_time
    fields:
        title:
            label: Event Name
            type: text
            class: large
            group: content
        slug:
            label: Slug
            type: slug
            uses: title
        event_time:
            label: Event Time
            type: datetime
            info: Input time in 24 hour format (select below the timezone that the time is meant to be in)
        event_time_zone:
            label: Event Time Timezone (Important!)
            info: Enter the timezone the above event time is meant to be in (need to know for the dynamic time display on the calendar/event pages)
            default: "America/Los_Angeles"
            type: timezone
            autocomplete: true
        time_display_mode:
            label: Event Time Display
            type: select
            values: {'local':"Local Event Time",'user':"Visitors Time",'both':"Both"}
            info: Changes how the event times are shown. It can show the time in the zone set above, or automatically adjust on the visitors end to show the time for their timezone, or both.
        location:
            label: Address / Geolocation
            type: geolocation
        web_location:
            label: Website Link URL
            type: text
            pattern: "url"
        web_location_title:
            label: Website Link Title (optional)
            type: text
        body:
            type: html
            height: 300px
    icon_many: fa:calendar