# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes

pages:
    name: Pages
    singular_name: Page
    description: Pages - available as /<page_slug> too
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: '*.twig'
    recordsperpage: 100
    icon_many: fa:file-text
    record_template: page.twig

members:
    name: Members
    singular_name: Member
    slug: members
    singular_slug: member
    fields:
        title:
            type: text
            class: large
            label: Name
            group: content
        slug:
            type: slug
            uses: title
        bio:
            type: markdown
        image:
            type: image
        youtube_channel_id:
            type: text
            label: Youtube Channel ID
            info: "24 character channel ID (eg. URL https://www.youtube.com/channel/[channel_id]). For yourself can be found on https://www.youtube.com/account_advanced"
            postfix: "<p>Youtube API will be queried for this ID to automatically update the fields bellow on page creation and once an hour.</p>"
            group: Youtube
        youtube_subscribers:
            type: biginteger
            label: Youtube Subscribers
        youtube_videos:
            type: integer
            label: Youtube Videos
        youtube_views:
            type: biginteger
            label: Youtube Views
        youtube_trailer:
            type: text
            label: Youtube Trailer Video ID
        youtube_uploads_playlist:
            type: text
            label: Youtube Channel Uploads Playlist ID
        primarily_twitch:
            type: checkbox
            label: Primarily Twitch? (the Sevadus switch)
        social_twitter_username:
            type: text
            label: Twitter Username
            group: Social Links
        social_reddit_username:
            type: text
            label: Reddit Username
        social_youtube_custom_name:
            type: text
            label: Youtube Custom Name (e.g. youtube.com/{ custom name } )
            info: If left empty, will just generate link the with the channel id, which is not exactly readable 
        social_twitch_username:
            type: text
            label: Twitch Username
    sort: title
    show_on_dashboard: false
    icon_many: fa:users
    icon_one: fa:user
    listing_records: 100

posts:
    name: News
    singular_name: News Item
    slug: news
    singular_slug: news-item
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        body:
            type: html
            height: 300px
        image:
            type: image
            attrib: title
    icon_many: fa:newspaper-o
    listing_records: 5

events:
    name: Events
    singular_name: Event
    listing_sort: -event_time
    sort: -event_time
    fields:
        title:
            label: Event Name
            type: text
            class: large
            group: content
        slug:
            label: Slug
            type: slug
            uses: title
        event_time:
            label: Event Time
            type: datetime
            info: Input time in 24 hour format (select below the timezone that the time is meant to be in)
        event_time_zone:
            label: Event Time Timezone (Important!)
            info: Enter the timezone the above event time is meant to be in (need to know for the dynamic time display on the calendar/event pages)
            default: "America/Los_Angeles"
            type: timezone
            autocomplete: true
        time_display_mode:
            label: Event Time Display
            type: select
            values: {'local':"Local Event Time",'user':"Visitors Time",'both':"Both"}
            info: Changes how the event times are shown. It can show the time in the zone set above, or automatically adjust on the visitors end to show the time for their timezone, or both.
        location:
            label: Address / Geolocation
            type: geolocation
        location_informal:
            label: Informal address (optional, shown in addition to formal address)
            info: For cases where the well known name of the building/location can be just as helpful as the actual address.
            type: text
        web_location:
            label: Website Link URL
            type: text
            pattern: "url"
        web_location_title:
            label: Website Link Title (optional)
            type: text
        body:
            type: html
            height: 300px
    icon_many: fa:calendar