# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
      path: /
    - label: News
      path: news
    - label: Calendar
      path: calendar
    - label: Members
      path: members
    - label: Podcast
      path: mindcrack-podcast
    - label: About
      path: about
    - label: Contact
      path: contact
    - label: Store
      path: https://store.mindcracklp.com
#    Removed until a store is set up

common_links:
    - label: Calendar
      path: calendar
      class: common-link-calendar
#    Replacement for store link
    # - label: News
    #   path: news
    #   class: common-link-news
    - label: Members
      path: members
      class: common-link-members
    - label: Store
      path: https://store.mindcracklp.com
      class: common-link-store