# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at
# http://docs.bolt.cm/templates-routes#routing

# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.



# ------------------------------------------------------------------------------
# These are the routes defining the default behaviour of Bolt's frontend.
# Changing these might give unexpected results or even break your website. If
# possible, only add NEW routes above or below these.

homepage:
    path: '/'
    defaults:
         _controller: controller.frontend:homepage
         template: 'home'

search:
    path: '/search'
    defaults:
        _controller: controller.frontend:search

preview:
    path: '/preview/{contenttypeslug}'
    defaults:
        _controller: controller.frontend:preview
    requirements:
        contenttypeslug: controller.requirement:anyContentType

contentlink:
    path: '/{contenttypeslug}/{slug}'
    defaults:
        _controller: controller.frontend:record
    requirements:
        contenttypeslug: controller.requirement:anyContentType

taxonomylink:
    path: '/{taxonomytype}/{slug}'
    defaults:
        _controller: controller.frontend:taxonomy
    requirements:
        taxonomytype: controller.requirement:anyTaxonomyType

contentlisting:
    path: '/{contenttypeslug}'
    defaults:
        _controller: controller.frontend:listing
    requirements:
        contenttypeslug: controller.requirement:pluralContentTypes

# ------------------------------------------------------------------------------
# Place your own routes here, that have a LOWER priority than the default routes.

calendar:
    path: '/calendar'
    defaults:
        _controller: 'Mindcrack\Site\Controllers\Calendar::upcoming'
        contentTypeSlug: 'events'
        template: 'calendar.twig'

pagebinding:
    path: /{slug}
    defaults:
        _controller: controller.frontend:record
        contenttypeslug: page
    contenttype: pages