# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at
# http://docs.bolt.cm/templates-routes#routing

# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.



# ------------------------------------------------------------------------------
# These are the routes defining the default behaviour of Bolt's frontend.
# Changing these might give unexpected results or even break your website. If
# possible, only add NEW routes above or below these.

homepage:
    path: '/'
    defaults:
         _controller: 'Bolt\Controllers\Frontend::homepage'
         template: 'home'

search:
    path: '/search'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::search'

preview:
    path: '/preview/{contenttypeslug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::preview'
    requirements:
        contenttypeslug: 'Bolt\Controllers\Routing::getAnyContentTypeRequirement'

contentlink:
    path: '/{contenttypeslug}/{slug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::record'
    requirements:
        contenttypeslug: 'Bolt\Controllers\Routing::getAnyContentTypeRequirement'

taxonomylink:
    path: '/{taxonomytype}/{slug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::taxonomy'
    requirements:
        taxonomytype: 'Bolt\Controllers\Routing::getAnyTaxonomyTypeRequirement'

contentlisting:
    path: '/{contenttypeslug}'
    defaults:
        _controller: 'Bolt\Controllers\Frontend::listing'
    requirements:
        contenttypeslug: 'Bolt\Controllers\Routing::getPluralContentTypeRequirement'

# ------------------------------------------------------------------------------
# Place your own routes here, that have a LOWER priority than the default routes.



