#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

$app = require __DIR__ . '/bootstrap.php';

/** @var Application $application retrieve the Nut Console Application from the Bolt application in the bootstrap */
$application = $app['nut'];
$application->run();
